/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvBuilderRouteImport } from './routes/cv-builder'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as BlogAutomatedTestingRouteImport } from './routes/blog.automated-testing'
import { Route as BlogEffectiveTestCasesRouteImport } from './routes/blog.effective-test-cases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvBuilderRoute = CvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAutomatedTestingRoute = BlogAutomatedTestingRouteImport.update({
  id: '/blog/automated-testing',
  path: '/blog/automated-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEffectiveTestCasesRoute = BlogEffectiveTestCasesRouteImport.update({
  id: '/blog/effective-test-cases',
  path: '/blog/effective-test-cases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv-builder': typeof CvBuilderRoute
  '/order': typeof OrderRoute
  '/templates': typeof TemplatesRoute
  '/blog/automated-testing': typeof BlogAutomatedTestingRoute
  '/blog/effective-test-cases': typeof BlogEffectiveTestCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv-builder': typeof CvBuilderRoute
  '/order': typeof OrderRoute
  '/templates': typeof TemplatesRoute
  '/blog/automated-testing': typeof BlogAutomatedTestingRoute
  '/blog/effective-test-cases': typeof BlogEffectiveTestCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv-builder': typeof CvBuilderRoute
  '/order': typeof OrderRoute
  '/templates': typeof TemplatesRoute
  '/blog/automated-testing': typeof BlogAutomatedTestingRoute
  '/blog/effective-test-cases': typeof BlogEffectiveTestCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv-builder'
    | '/order'
    | '/templates'
    | '/blog/automated-testing'
    | '/blog/effective-test-cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv-builder'
    | '/order'
    | '/templates'
    | '/blog/automated-testing'
    | '/blog/effective-test-cases'
  id:
    | '__root__'
    | '/'
    | '/cv-builder'
    | '/order'
    | '/templates'
    | '/blog/automated-testing'
    | '/blog/effective-test-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvBuilderRoute: typeof CvBuilderRoute
  OrderRoute: typeof OrderRoute
  TemplatesRoute: typeof TemplatesRoute
  BlogAutomatedTestingRoute: typeof BlogAutomatedTestingRoute
  BlogEffectiveTestCasesRoute: typeof BlogEffectiveTestCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-builder': {
      id: '/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof CvBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/automated-testing': {
      id: '/blog/automated-testing'
      path: '/blog/automated-testing'
      fullPath: '/blog/automated-testing'
      preLoaderRoute: typeof BlogAutomatedTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/effective-test-cases': {
      id: '/blog/effective-test-cases'
      path: '/blog/effective-test-cases'
      fullPath: '/blog/effective-test-cases'
      preLoaderRoute: typeof BlogEffectiveTestCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvBuilderRoute: CvBuilderRoute,
  OrderRoute: OrderRoute,
  TemplatesRoute: TemplatesRoute,
  BlogAutomatedTestingRoute: BlogAutomatedTestingRoute,
  BlogEffectiveTestCasesRoute: BlogEffectiveTestCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
